version: '3'
services:

  postgrest:
    image: postgrest/postgrest:v7.0.1
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://postgres:enduro@postgres:5432/enduro
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres # In production this role should not be the same as the one used for the connection
    depends_on:
      - postgres
      - swagger

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 9000:8080
    environment:
      API_URL: http://localhost:3000

  postgres:
    image: bitnami/postgresql:9.6
    environment:
      POSTGRESQL_DATABASE: enduro
      POSTGRESQL_PASSWORD: enduro
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql