version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: "%(asctime)s %(levelname)-8s %(filename)s:%(lineno)d: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [ console ]