apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: postgrest
spec:
  type: ClusterIP
  selector:
    app: postgrest
  ports:
    - name: postgrest
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: swagger
      protocol: TCP
      port: 3001
      targetPort: 8080
