apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: postgrest
spec:
  type: ClusterIP
  selector:
    app: postgrest
  ports:
    - name: HTTP
      protocol: TCP
      port: 80
      targetPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: swagger
  namespace: postgrest
spec:
  type: ClusterIP
  selector:
    app: postgrest
  ports:
    - name: HTTP
      protocol: TCP
      port: 80
      targetPort: 8080