apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgrest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mkue/enduro
    path: k8s/namespaces/postgrest
    targetRevision: master
    helm: { }
  destination:
    server: https://kubernetes.default.svc
    namespace: postgrest
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
