apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:mkue/enduro.git
    path: k8s/namespaces/postgresql
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy: {}
